global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'cloudmesh-monitor'

scrape_configs:
  # CloudMesh Pushgateway
  - job_name: 'cloudmesh-pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: /metrics
    honor_labels: true
    honor_timestamps: true

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Pushgateway self-monitoring
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    scrape_interval: 30s
